<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Core" Version="5.4.21" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.11.19" NoWarn="NU1701" />
		<PackageReference Include="Mono.Cecil" Version="0.11.6" />
		<PackageReference Include="MonoMod.Utils" Version="22.1.29.1" />
		<PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0-r.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="UnityEngine">
			<HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <None Update="eliteWeights.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
